### ISSUE TITLE
OAuth: Github

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-client#9]
@green9016 I know that Login with Github is working, I think we'd like each of these Login options to be a component that will be displayed if that login option is enabled in a config.json file
Please add to the line form to display login strategies that are enabled in config, we should have a config for frontend, otherwise just create a config.json

**Comment by dmitrizagidulin** [comment]
@green9016 Logging in with Github OAuth doesn't seem to be working for me.

My backend: http://localhost:3030
My frontend: http://localhost:3000

I registered the app with Github oauth, got a CLIENT_ID and CLIENT_SECRET. Put those in to the config file.

Starting up client & server, click on Github icon, Github OAuth dialog appears (asks to give access to the app), I click Authorize.

My registered callback url: `http://localhost:3030/oauth/github/callback`

Then it gets stuck at:

`http://localhost:3030/oauth/github/authenticate?token=eyJh...`

(Too may redirects).

So, couple of questions. 1) Are there config steps I'm missing? 2) Is the callback URL supposed to be port 3030 (that is, point to the server, instead of the client)? I'm guessing yes.

**Comment by green9016** [comment]
Hello @shawticus @dmitrizagidulin 
I think github oauth was finished a few day ago.

**Comment by shawticus** [comment]
@green9016 Did @dmitrizagidulin 's questions get answered from previous comment?

**Comment by green9016** [comment]
@shawticus @dmitrizagidulin 
Yes. To github oauth, you need to config the GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, GITHUB_CALLBACK_URL.

backend: http://localhost:3030
frontend: http://localhost:3000

1) You missed GITHUB_CALLBACK_URL=http://localhost:3000/oauth/github configuration in backend.
2) Same question. Callback url port should be the client port. So the port is 3000.

**Comment by shawticus** [comment]
Closing this issue.
